name: flutter_ho
description: Flutter 脚手架
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  # 权限请求
  permission_handler: ^5.0.1+1

  #App版本信息
  package_info: ^0.4.3+2
  #用来加载网络数据
  dio: 3.0.9
  # WebView
  webview_flutter: ^1.0.7

  #偏好设置
  shared_preferences: ^0.5.12+4

  # 饼图
  flutter_echart: ^1.0.2
    #path: /Volumes/code/ico/Desktop/code/flutter_app/flutter_echart

  # 路径获取
  path_provider: ^1.6.24
  #视频播放
  video_player: ^1.0.1
  #toast 消息提示小弹框
  fluttertoast: ^7.0.1+1

  #  APP升级安装组件 Android中调用自动安装 apk的程序
  #ios 调用打开APPStore
  install_plugin_custom:
    git:
      url: https://github.com/zhaolongs/install_plugin_custom.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/images/app_icon.png
    - assets/images/
    - assets/video/